admin:
  # For GRPC endpoints you might want to use dns:///flyte.myexample.com
  endpoint: dns:///localhost:30081
  insecure: true
logger:
  show-source: true
  level: 3
storage:
  connection:
    access-key: minio
    auth-type: accesskey
    disable-ssl: true
    endpoint: http://localhost:9000
    region: my-region-here
    secret-key: miniostorage
  cache:
    max_size_mbs: 10
    target_gc_percent: 100
  container: my-container
  type: minio